name = "lastfm-shields-dev"
type = "webpack"
account_id = "4ae2b0231430be3b4de63e32381d6513"
zone_id = "af76b9090f6e819df8e36ba0d850b2fd"
workers_dev = true
vars = { USER = "zero-vortex" }

[dev]
ip = "0.0.0.0"
port = 9000
local_protocol="http"
upstream_protocol="https"

[env.production]
name = "lastfm-shields"
workers_dev = false
route = "workers.vortex.name/lastfm/endpoint.json"
vars = { USER = "zero-vortex" }
